### ISSUE TITLE
after composer update error in file upload

### ISSUE THREAD

**Issue by washeul** [msurguy/missingpetflyer#3]
when i do composer update the file upload functionality not working properly , the file its been save in the uploads file but not fetch in ui gives an error "error in file upload"

![untitled](https://cloud.githubusercontent.com/assets/6375092/3408434/3c78f616-fdc9-11e3-8bb9-ec4980c3c992.jpg)

**Comment by msurguy** [comment]
Could you open up Web Developer tools in Chrome , go to network tab, refresh that page and try to upload an image again? It should give you an error on that request, I'd like you to make a screenshot of the error and paste it here please.

Thanks!

**Comment by washeul** [comment]
actually i do not have that code right now & that issue was fixed by changing the "intervention/image": "dev-master"  to   "intervention/image": "1.6.5" then after composer update it was working fine :)
